Pierwsza wersja dokumentacji panelu administracyjnego
snowbeltIO/docs pull request #2
Opened 2020-09-27 15:29 UTC by SmietankowyImperator

2020-09-29 21:10 UTC, magul requested changes
W artykułach zmienił się ekran listy, w sumie wszytkie do kosmetycznej poprawy

2020-09-29 21:10 UTC, magul commented on docs/doc1.md
> +#### Articles
```
## Artykuły (Articles)

#### Artykuły (Articles)

Klikając w `Articles` w menu bocznym przechodzimy do ekranu listy artykułów.
Na górze ekranu listy widnieje przycisk dodawania artykułu (`Add article`).
Na liście klikając w pojedynczy artykuł przechodzimy do ekranu edycji artukułu.
W panelu akcji dotyczącym pojedynczego artykułu znajduje się ikona pozwalająca usunąć artykuł.


Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Subscriber` - subskrybent
* `Title` - tytuł artykułu
* `Text` - treść artykułu
* `Photo` - zdjęcie występujące w nagłówku artykułu
Na ekranie dostępne są 3 przyciski:
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy artykułów
* `Save and add another` - zapisujemy zmiany i przechodzimy do ekranu dodwania nowego artykułu
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranego artykułu

Po utworzeniu nowych artykułów możemy je na stałe przypiąć do menu aplikacji.
```

2020-09-29 22:24 UTC, SmietankowyImperator commented
kurka, nie wiem jak to teraz poprawić więc zostawie sobie to co napisałem w komentarzu

```
---
id: doc1
title: Strona panelu administracyjnego
sidebar_label: Panel administracyjny
---

## Artykuły (Articles)

#### Artykuły (Articles)

Klikając w `Articles` w menu bocznym przechodzimy do ekranu listy artykułów.
Na górze ekranu listy widnieje przycisk dodawania artykułu (`Add article`).
Na liście klikając w pojedynczy artykuł przechodzimy do ekranu edycji artukułu.
W panelu akcji dotyczącym pojedynczego artykułu znajduje się ikona pozwalająca usunąć artykuł.


Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Subscriber` - subskrybent
* `Title` - tytuł artykułu
* `Text` - treść artykułu
* `Photo` - zdjęcie występujące w nagłówku artykułu
Na ekranie dostępne są 3 przyciski:
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy artykułów
* `Save and add another` - zapisujemy zmiany i przechodzimy do ekranu dodwania nowego artykułu
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranego artykułu

Po utworzeniu nowych artykułów możemy je na stałe przypiąć do menu aplikacji.

***

## Galerie (Galleries)

#### Galerie (Galleries)

Klikając w `Galleries` w menu bocznym przechodzimy do ekranu listy galerii.
Na górze ekranu listy widnieje przycisk dodawania galerii (`Add Gallery`).
Na liście klikając w pojedynczą galerieę przechodzimy do ekranu edycji galerii.
W panelu akcji dotyczącym pojedynczej galerii znajduje się ikona pozwalająca usunąć galerię.


Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Name` - nazwa galerii
* `Published at` - należy zdefiniować datę i godzinę publikacji galerii
* Zdjęcia dodajemy i sortujemy w galeri przeciągając i upuszczając w odpowiednie miejsca
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy galerii

***

## Aktualności (News)

#### Aktualności (News)

Klikając w `News` w menu bocznym przechodzimy do ekranu listy aktualności.
Na górze ekranu listy widnieje przycisk dodawania aktualności (`Add news`).
Na liście klikając w pojedynczą aktualność przechodzimy do ekranu edycji aktualności.
W panelu akcji dotyczącym pojedynczej aktualności znajduje się ikona pozwalająca usunąć aktualność.

Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Subscriber` - subskrybent
* `Title` - tytuł aktualności
* `Text` - treść aktualności
* `Photo` - zdjęcie występujące w nagłówku aktualności
* `Published at:` - określa datę oraz godzinę publikacji aktualności
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy aktualności
* `Save and add another` - zapisujemy zmiany i przechodzimy do ekranu dodwania nowej aktualności
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranej aktualności

Nowe aktualności pojawiają się automatycznie w głównym oknie aplikacji zgodnie z ustaloną datą i godziną.

***

## Subskrybenci (Subscribers)

#### Obiekt menu (Menu entitys)

Klikając w `Menu entitys` w menu bocznym przechodzimy do ekranu listy obiektow menu
Na górze ekranu listy widnieje przycisk dodawania obiektów menu (`Add Menu entity`).
Na liście klikając w pojedynczy obiekt menu przechodzimy do ekranu edycji obiektu menu.

Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Subscriber` - subskrybent
* `Title` - Nazwa obieku menu
* `Content type` - typ nowego elementu menu
* `Article` - po wyborze `Article` w sekcji `Content type` należy wybrać który artykuł ma zostać przypięty jako element menu
* `Team list` - po wyborze z rozwijanej listy`Team list` w sekcji `Content type` należy wybrać który zespół ma zostać przypięty jako element menu
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy elementów menu
* `Save and add another` - zapisujemy zmiany i przechodzimy do ekranu dodwania nowego elementu menu
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranego elemtnu menu

#### Następne spotkanie (Next matches)

Klikając w `Next matches` w menu bocznym przechodzimy do ekranu listy przyszłych spotkań.
Na górze ekranu listy przyszłych spotkań widnieje przycisk dodawania następnęgo spotkania (`add next match`).
Na liście klikając w pojedyncze przyszłe spotkanie przechodzimy do ekranu edycji następnego spotkania.
W panelu akcji dotyczącym pojedynczego przyszłego spotkania znajduje się ikona pozwalająca usunąć nastepne spotkanie.

Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Subscriber` - subskrybent
* `Played at:` - określa datę i godzinę następnego spotkania
* `Oponent Name` - nazwa drużyny przeciwnej
* `Opponent crest` - herb drużyny przeciwnej
* `Venue name` - nazwa stadionu gospodarza
* `Venue address` - adres stadionu gospodarza
* `Venue city` - miasto gospodarza
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy nastepnych spotkań
* `Save and add another` - zapisujemy zmiany i przechodzimy do ekranu dodwania następnego spotkania
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranego następnego spotkania

#### Partnerzy (Partners)

Klikając w `Parnters` w menu bocznym przechodzimy do ekranu listy partnerów.
Na górze ekranu listy widnieje przycisk dodawania partnera (`Add partner`).
Na liście klikając w pojedynczego partnera przechodzimy do ekranu edycji partnera.
W panelu akcji dotyczącym pojedynczego partnera znajduje się ikona pozwalająca usunąć partnera.

Na ekranie dodawania lub edycji znajdują się następujące pola:
* `Subscriber` - subskrybent
* `Name` - nazwa partnera
* `Logo` - logo partnera
* `Homepage` - link do strony partnera
* `Save` - zapisujemy zmiany i przechodzimy na ekran listy partnerów
* `Save and add another` - zapisujemy zmiany i przechodzimy do ekranu dodwania partnerów
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranego partnera

#### Subskrybent (Subscribers)

Klikając w `Subscriber` w menu bocznym przechodzimy do ekranu listy subskrybentów
Na liście klikając w subskrybenta przechodzimy do ekranu edycji subskrybenta.

Na ekranie edycji znajdują się następujące pola:
* `Name` nazwa klubu sportowego
* `Crest` pozwala wgrać herb klubu sportowego
* `Email` - adres email klubu sportowego
* `Phone` - numer telefonu do klubu sportowego
* `Longitude` - długość geograficzna adresu klubu kportowego
* `Latitude` - wysokość geograficzna adresu klubu sportowego
* `Address` - adres klubu sportowego
* `Zipcode` - kod pocztowy adresu klubu sportowego
* `City` - miasto klubu sportowego

1. `PARTNERS` służy do sortowania partnerów w żądanej kolejności wyświetlania
2. `MENU ENTITYS`- służy do sortowania elemntów menu w żądanej kolejności wyświetlania

* `Save` - zapisujemy zmiany i przechodzimy na ekran listy subskrybentów
* `Save and continue editing` - zapisujemy i kontynuujemy edycję wybranego subskrybenta

```

2020-10-16 09:33 UTC, magul approved these changes

2020-10-16 09:33 UTC, merged